# Generated by Django 2.2.3 on 2019-08-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('disputed', models.BooleanField(default=False)),
                ('grape', models.IntegerField(default=0)),
                ('orange', models.IntegerField(default=0)),
                ('blue_punch', models.IntegerField(default=0)),
                ('lemon_lime', models.IntegerField(default=0)),
                ('pina_colada', models.IntegerField(default=0)),
                ('banana', models.IntegerField(default=0)),
                ('peach', models.IntegerField(default=0)),
                ('cherry', models.IntegerField(default=0)),
                ('mango', models.IntegerField(default=0)),
                ('green_apple', models.IntegerField(default=0)),
                ('watermelon', models.IntegerField(default=0)),
                ('strawberry', models.IntegerField(default=0)),
                ('guava', models.IntegerField(default=0)),
                ('mojito', models.IntegerField(default=0)),
                ('papaya', models.IntegerField(default=0)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Charge')),
            ],
        ),
    ]
